server:
  port: 8081
spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/springcloud_order?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: password
  redis:
    host: 127.0.0.1
    port: 6379
    #    password: 123456
    database: 3
mybatis:
  mapper-locations:
    - classpath*:mappers/**/*.xml
  configuration:
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
    #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true
  type-aliases-package: net.seehope.order.pojo.order
logging:
  level:
    org.springframework: info
    net.seehope: debug
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka
